/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/policies/parse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Parse Policy */
    post: operations["parse_policy_policies_parse_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Portfolio Session */
    post: operations["create_portfolio_session_portfolio_sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/sessions/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh Portfolio Session */
    post: operations["refresh_portfolio_session_portfolio_sessions_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/sessions/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete Portfolio Session */
    post: operations["delete_portfolio_session_portfolio_sessions_delete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/sessions/documents/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete Portfolio Session Documents */
    post: operations["delete_portfolio_session_documents_portfolio_sessions_documents_delete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Coverage Summary */
    post: operations["coverage_summary_portfolio_summary_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Summary Overview */
    post: operations["summary_overview_portfolio_overview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/qa/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stream Qa Answer
     * @description Resolve the session, then stream one agent's answer as SSE.
     */
    post: operations["stream_qa_answer_qa_stream_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActualLossCoverageItem */
    ActualLossCoverageItem: {
      /** Policy Id */
      policy_id: string | null;
      /** Insurer */
      insurer: string | null;
      /** Product Name */
      product_name: string | null;
      /** Coverage Name */
      coverage_name: string;
      /** Normalized Name */
      normalized_name: string;
      /**
       * Coverage Domain
       * @enum {string}
       */
      coverage_domain:
        | "medical_expense"
        | "travel_medical_expense"
        | "legal_cost"
        | "property_damage"
        | "liability"
        | "auto"
        | "other";
      /** Is Medical Indemnity */
      is_medical_indemnity: boolean;
      /** Is Damage Policy */
      is_damage_policy: boolean;
      /** Duplicate Across Contracts */
      duplicate_across_contracts: boolean;
      /**
       * Guidance Key
       * @enum {string}
       */
      guidance_key:
        | "injury_medical_expense"
        | "disease_medical_expense"
        | "inpatient_medical_expense"
        | "outpatient_medical_expense"
        | "prescription_medical_expense"
        | "medical_expense"
        | "travel_medical_expense"
        | "legal_cost"
        | "property_damage"
        | "liability"
        | "auto"
        | "other";
      /** Explanation */
      explanation: string;
      /**
       * Explanation Basis
       * @constant
       */
      explanation_basis: "generated_guidance";
      /**
       * Original Amount
       * @default
       */
      original_amount: string;
      /**
       * Major Category
       * @default 기타
       */
      major_category: string;
    };
    /** @enum {string} */
    ApiErrorCode:
      | "PDF_TOO_LARGE"
      | "PDF_PAGE_LIMIT_EXCEEDED"
      | "PDF_COMPLEXITY_LIMIT_EXCEEDED"
      | "PDF_PARSING_BUSY"
      | "INVALID_PDF"
      | "PDF_PASSWORD_REQUIRED"
      | "PDF_PASSWORD_INCORRECT"
      | "PDF_TEXT_EXTRACTION_FAILED"
      | "reference_data_unavailable"
      | "portfolio_overview_unavailable"
      | "INVALID_PORTFOLIO_SESSION"
      | "PORTFOLIO_DOCUMENT_LIMIT_EXCEEDED"
      | "COUNSEL_TURN_LIMIT_REACHED"
      | "POLICY_UPLOAD_IN_PROGRESS"
      | "POLICY_UPLOAD_ALREADY_COMPLETED"
      | "POLICY_UPLOAD_CANCELLED"
      | "portfolio_session_unavailable"
      | "INVALID_POLICY_SELECTION"
      | "REQUEST_VALIDATION_ERROR"
      | "INVALID_MULTIPART_REQUEST"
      | "HTTP_ERROR"
      | "INTERNAL_SERVER_ERROR";
    /** ApiErrorDetail */
    ApiErrorDetail: {
      code: components["schemas"]["ApiErrorCode"];
      /** Message */
      message: string;
      /** Request Id */
      request_id: string;
    };
    /** ApiErrorResponse */
    ApiErrorResponse: {
      error: components["schemas"]["ApiErrorDetail"];
    };
    /** Body_parse_policy_policies_parse_post */
    Body_parse_policy_policies_parse_post: {
      /**
       * File
       * Format: binary
       * @description PDF document only. The server verifies the %PDF signature and accepts at most 10 MiB and 100 pages.
       */
      file: string;
      /**
       * Documentid
       * Format: uuid
       */
      documentId: string;
      /** Password */
      password?: string | null;
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
    };
    /** ClaimChannelBlock */
    ClaimChannelBlock: {
      /** Insurers */
      insurers?: components["schemas"]["ClaimChannelInsurer"][];
      medical_indemnity?:
        components["schemas"]["ClaimChannelMedicalIndemnity"] | null;
    };
    /** ClaimChannelInsurer */
    ClaimChannelInsurer: {
      /** Name */
      name: string;
      /** Customer Center */
      customer_center?: string | null;
      /** Note */
      note?: string | null;
      /** Links */
      links?: components["schemas"]["ClaimChannelLink"][];
    };
    /** ClaimChannelLink */
    ClaimChannelLink: {
      /** Label */
      label: string;
      /** Url */
      url: string;
    };
    /** ClaimChannelMedicalIndemnity */
    ClaimChannelMedicalIndemnity: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Call Center */
      call_center?: string | null;
      /** Links */
      links?: components["schemas"]["ClaimChannelLink"][];
    };
    /**
     * Coverage
     * @description Public coverage contract with explicit verification and row type state.
     */
    Coverage: {
      /** 담보명 */
      "\uB2F4\uBCF4\uBA85": string;
      /** 가입금액 */
      "\uAC00\uC785\uAE08\uC561": string;
      /**
       * 가입금액상태
       * @enum {string}
       */
      "\uAC00\uC785\uAE08\uC561\uC0C1\uD0DC":
        "confirmed" | "needs_review" | "not_applicable";
      /** 보장내용 */
      "\uBCF4\uC7A5\uB0B4\uC6A9": string | null;
      /** 해설 */
      "\uD574\uC124": string | null;
      /**
       * 설명근거
       * @enum {string}
       */
      "\uC124\uBA85\uADFC\uAC70":
        "policy_wording" | "generated_guidance" | "none";
      /**
       * 유형
       * @enum {string}
       */
      "\uC720\uD615": "담보" | "부가";
    };
    /** CoverageGroup */
    CoverageGroup: {
      /** Label */
      label: string;
      /**
       * Tone
       * @enum {string}
       */
      tone: "confirmed" | "review" | "limited";
      /** Detail */
      detail: string;
      /** Coverage Names */
      coverage_names?: string[];
      /** Total Amount */
      total_amount?: number | null;
    };
    /** CoveragePeriod */
    CoveragePeriod: {
      /** 시작일 */
      "\uC2DC\uC791\uC77C"?: string;
      /** 종료일 */
      "\uC885\uB8CC\uC77C"?: string;
    };
    /** CoverageSourceItem */
    CoverageSourceItem: {
      /** Policy Id */
      policy_id: string | null;
      /** Insurer */
      insurer: string | null;
      /** Product Name */
      product_name: string | null;
      /** Coverage Name */
      coverage_name: string;
      /** Amount */
      amount: number;
      /** Original Amount */
      original_amount: string;
    };
    /** CoverageTotalItem */
    CoverageTotalItem: {
      /** Normalizedname */
      normalizedName: string;
      /** Category */
      category: string;
      /** Majorcategory */
      majorCategory: string;
      /** Totalamount */
      totalAmount: number;
      /** Coveragecount */
      coverageCount: number;
      /** Composition */
      composition: components["schemas"]["CoverageSourceItem"][];
    };
    /** DamageCoverageGroup */
    DamageCoverageGroup: {
      /** Insurance Type */
      insurance_type: string;
      /** Policies */
      policies: components["schemas"]["DamagePolicyCoverageGroup"][];
    };
    /** DamageCoverageItem */
    DamageCoverageItem: {
      /** Coverage Name */
      coverage_name: string;
      /** Original Amount */
      original_amount: string;
      /**
       * Major Category
       * @default 기타
       */
      major_category: string;
    };
    /** DamagePolicyCoverageGroup */
    DamagePolicyCoverageGroup: {
      /** Policy Id */
      policy_id: string | null;
      /** Insurer */
      insurer?: string | null;
      /** Product Name */
      product_name?: string | null;
      /** Coverages */
      coverages: components["schemas"]["DamageCoverageItem"][];
    };
    /** DeathBenefitGuideInput */
    DeathBenefitGuideInput: {
      /**
       * Has Dependent Family
       * @default false
       */
      has_dependent_family: boolean;
      /**
       * Has Minor Children
       * @default false
       */
      has_minor_children: boolean;
      /**
       * Has Major Debt
       * @default false
       */
      has_major_debt: boolean;
    };
    /** EssentialCoverageCheck */
    EssentialCoverageCheck: {
      /** Items */
      items: components["schemas"]["EssentialCoverageItem"][];
    };
    /** EssentialCoverageItem */
    EssentialCoverageItem: {
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | "death"
        | "cancer"
        | "cerebrovascular"
        | "ischemic_heart"
        | "medical_indemnity";
      /** Label */
      label: string;
      /**
       * Status
       * @enum {string}
       */
      status: "well_prepared" | "needs_review" | "not_found";
      /** Confirmed Amount */
      confirmed_amount?: number | null;
      /** Reference Min Amount */
      reference_min_amount?: number | null;
      /** Reference Max Amount */
      reference_max_amount?: number | null;
      /** Reference Basis */
      reference_basis?: string | null;
      /** Reference Sources */
      reference_sources?: components["schemas"]["ReferenceSource"][];
      /** Reference Amount Label */
      reference_amount_label?: string | null;
      /** Guidance Situation */
      guidance_situation?: string | null;
      /** Guidance Reason */
      guidance_reason?: string | null;
      /** Coverage Count */
      coverage_count: number;
      /** Detail */
      detail: string;
      /** Matched Coverage Names */
      matched_coverage_names?: string[];
      /** Coverage Groups */
      coverage_groups?: components["schemas"]["CoverageGroup"][];
    };
    /** ExcludedCoverageItem */
    ExcludedCoverageItem: {
      /** Policy Id */
      policy_id: string | null;
      /** Coverage Name */
      coverage_name: string;
      /** Original Amount */
      original_amount: string;
      /** Reason */
      reason: string;
      /** Insurer */
      insurer?: string | null;
      /** Product Name */
      product_name?: string | null;
      /**
       * Major Category
       * @default 기타
       */
      major_category: string;
    };
    /**
     * InsuredDemographics
     * @description Non-identifying insured attributes derived locally from the policy.
     */
    InsuredDemographics: {
      /** 나이 */
      "\uB098\uC774": number;
      /**
       * 성별
       * @enum {string}
       */
      "\uC131\uBCC4": "남성" | "여성";
      /**
       * 생애단계
       * @enum {string}
       */
      "\uC0DD\uC560\uB2E8\uACC4": "어린이" | "성인" | "시니어";
    };
    /** PolicyParseResponse */
    PolicyParseResponse: {
      /**
       * Status
       * @constant
       */
      status: "accepted";
      /**
       * Documentid
       * Format: uuid
       */
      documentId: string;
      /** 문자수 */
      "\uBB38\uC790\uC218": number;
      "\uAE30\uBCF8\uC815\uBCF4": components["schemas"]["PolicySummary"];
      /** 보장목록 */
      "\uBCF4\uC7A5\uBAA9\uB85D": components["schemas"]["Coverage"][];
      /**
       * 분석상태
       * @enum {string}
       */
      "\uBD84\uC11D\uC0C1\uD0DC": "완료" | "부분";
      /**
       * Policy Terms Status
       * @default unavailable
       * @enum {string}
       */
      policy_terms_status: "available" | "unavailable";
    };
    /**
     * PolicySummary
     * @description Public policy summary with canonical classification metadata.
     */
    PolicySummary: {
      /**
       * 보험분류
       * @enum {string}
       */
      "\uBCF4\uD5D8\uBD84\uB958":
        "생명보험" | "제3보험" | "손해보험" | "미분류";
      /** 상품태그 */
      "\uC0C1\uD488\uD0DC\uADF8": string[];
      /** 보험사 */
      "\uBCF4\uD5D8\uC0AC"?: string | null;
      /** 상품명 */
      "\uC0C1\uD488\uBA85"?: string | null;
      /** 증권번호 */
      "\uC99D\uAD8C\uBC88\uD638"?: string | null;
      /** 계약자 */
      "\uACC4\uC57D\uC790"?: string | null;
      /** 피보험자 */
      "\uD53C\uBCF4\uD5D8\uC790"?: string | null;
      "\uBCF4\uD5D8\uAE30\uAC04"?:
        components["schemas"]["CoveragePeriod"] | null;
      /** 만기일 */
      "\uB9CC\uAE30\uC77C"?: string | null;
      /** 납입기간 */
      "\uB0A9\uC785\uAE30\uAC04"?: string | null;
      "\uBCF4\uD5D8\uB8CC"?: components["schemas"]["PremiumSummary"] | null;
      "\uD53C\uBCF4\uD5D8\uC790\uC815\uBCF4"?:
        components["schemas"]["InsuredDemographics"] | null;
      "\uCC28\uB7C9\uC815\uBCF4"?: components["schemas"]["VehicleInfo"] | null;
    };
    /** PortfolioCoverageSummary */
    PortfolioCoverageSummary: {
      /** Totals */
      totals: components["schemas"]["CoverageTotalItem"][];
      /** Actual Loss Coverages */
      actual_loss_coverages: components["schemas"]["ActualLossCoverageItem"][];
      /** Excluded Coverages */
      excluded_coverages: components["schemas"]["ExcludedCoverageItem"][];
      /** Damage Coverages */
      damage_coverages?: components["schemas"]["DamageCoverageGroup"][];
      /** Excluded Auto Policy Count */
      excluded_auto_policy_count: number;
      essential_coverage_check?: components["schemas"]["EssentialCoverageCheck"];
      /** Special Policy Analyses */
      special_policy_analyses?: components["schemas"]["SpecialPolicyAnalysis"][];
      claim_channels?: components["schemas"]["ClaimChannelBlock"] | null;
      premium?: components["schemas"]["PremiumOverview"] | null;
      premium_benchmark?: components["schemas"]["PremiumBenchmark"] | null;
      overview?: components["schemas"]["PortfolioOverview"] | null;
    };
    /** PortfolioOverview */
    PortfolioOverview: {
      /**
       * Generation
       * @constant
       */
      generation: "llm";
      /** Title */
      title: string;
      /** Paragraphs */
      paragraphs?: string[];
    };
    /** PortfolioSessionDeleteResponse */
    PortfolioSessionDeleteResponse: {
      /**
       * Status
       * @constant
       */
      status: "deleted";
    };
    /** PortfolioSessionDocumentsDeleteRequest */
    PortfolioSessionDocumentsDeleteRequest: {
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
      /** Documentids */
      documentIds: string[];
    };
    /** PortfolioSessionRequest */
    PortfolioSessionRequest: {
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
    };
    /** PortfolioSessionResponse */
    PortfolioSessionResponse: {
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
      /** Expiresat */
      expiresAt: string;
      /** Counselturnsremaining */
      counselTurnsRemaining: number;
    };
    /** PortfolioSummaryRequest */
    PortfolioSummaryRequest: {
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
      /** Policyids */
      policyIds: string[];
      death_benefit_context?: components["schemas"]["DeathBenefitGuideInput"];
    };
    /** PremiumBenchmark */
    PremiumBenchmark: {
      /** Age Band Label */
      age_band_label: string;
      /** Min Age */
      min_age: number;
      /** Max Age */
      max_age: number;
      /** Average Monthly Income */
      average_monthly_income: number;
      /** Suggested Min Ratio */
      suggested_min_ratio: number;
      /** Suggested Max Ratio */
      suggested_max_ratio: number;
      /** Suggested Min Premium */
      suggested_min_premium: number;
      /** Suggested Max Premium */
      suggested_max_premium: number;
      income_source: components["schemas"]["ReferenceSource"];
      guide_source: components["schemas"]["ReferenceSource"];
    };
    /** PremiumOverview */
    PremiumOverview: {
      /** Monthly Total */
      monthly_total: number;
      /** Monthly Policy Count */
      monthly_policy_count: number;
      /** Unconfirmed Policy Count */
      unconfirmed_policy_count: number;
      /** Items */
      items: components["schemas"]["PremiumPolicyItem"][];
    };
    /** PremiumPolicyItem */
    PremiumPolicyItem: {
      /** Policy Id */
      policy_id: string | null;
      /** Insurer */
      insurer: string | null;
      /** Product Name */
      product_name: string | null;
      /** Monthly Amount */
      monthly_amount: number | null;
      /** Cycle */
      cycle: string | null;
    };
    /** PremiumSummary */
    PremiumSummary: {
      /** 금액 */
      "\uAE08\uC561"?: number;
      /** 납입주기 */
      "\uB0A9\uC785\uC8FC\uAE30"?: string;
    };
    /** QaDeltaEvent */
    QaDeltaEvent: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "delta";
      /** Text */
      text: string;
    };
    /** QaEndEvent */
    QaEndEvent: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "end";
    };
    /** QaErrorEvent */
    QaErrorEvent: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "error";
      /**
       * Code
       * @constant
       */
      code: "QA_STREAM_FAILED";
      /** Message */
      message: string;
      /** Request Id */
      request_id: string;
      /** Retryable */
      retryable: boolean;
    };
    /** QaMessage */
    QaMessage: {
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant";
      /** Content */
      content: string;
    };
    /** QaMetaEvent */
    QaMetaEvent: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "meta";
      /** In Scope */
      in_scope: boolean;
      /** Answered Question */
      answered_question: string;
      /** Excluded Note */
      excluded_note: string | null;
      /** Turns Remaining */
      turns_remaining: number;
    };
    /** QaRequest */
    QaRequest: {
      /** Question */
      question: string;
      /** History */
      history?: components["schemas"]["QaMessage"][];
      /** Session Id */
      session_id: string;
    };
    /** ReferenceSource */
    ReferenceSource: {
      /** Label */
      label: string;
      /** Url */
      url: string;
      /** Published At */
      published_at: string;
      /**
       * Reliability
       * @enum {string}
       */
      reliability:
        | "official"
        | "public_research"
        | "industry"
        | "large_private_analysis"
        | "private_guidance";
      /** Caveat */
      caveat: string;
    };
    /** SpecialCoverageCheck */
    SpecialCoverageCheck: {
      /** Label */
      label: string;
      /**
       * Status
       * @enum {string}
       */
      status: "confirmed" | "not_found";
      /** Detail */
      detail: string;
      /** Matched Coverage Names */
      matched_coverage_names?: string[];
    };
    /** SpecialPolicyAnalysis */
    SpecialPolicyAnalysis: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "auto" | "driver" | "travel" | "fire";
      /** Label */
      label: string;
      /** Policy Count */
      policy_count: number;
      /** Product Names */
      product_names?: string[];
      /** Confirmed Coverage Names */
      confirmed_coverage_names?: string[];
      /** Classification Reasons */
      classification_reasons?: string[];
      /** Overview */
      overview: string;
      /** Coverage Checks */
      coverage_checks?: components["schemas"]["SpecialCoverageCheck"][];
    };
    /**
     * VehicleInfo
     * @description Vehicle details extracted from policy summary.
     */
    VehicleInfo: {
      /** 차량명 */
      "\uCC28\uB7C9\uBA85"?: string;
      /** 차량번호 */
      "\uCC28\uB7C9\uBC88\uD638"?: string;
      /** 연식 */
      "\uC5F0\uC2DD"?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  parse_policy_policies_parse_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_parse_policy_policies_parse_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PolicyParseResponse"];
        };
      };
      /** @description Coverly API error */
      400: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      404: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      405: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      409: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      413: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      500: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  create_portfolio_session_portfolio_sessions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioSessionResponse"];
        };
      };
      /** @description Coverly API error */
      404: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      405: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      500: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  refresh_portfolio_session_portfolio_sessions_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioSessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioSessionResponse"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      404: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      405: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      500: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  delete_portfolio_session_portfolio_sessions_delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioSessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioSessionDeleteResponse"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      404: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      405: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      500: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  delete_portfolio_session_documents_portfolio_sessions_documents_delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioSessionDocumentsDeleteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioSessionDeleteResponse"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      404: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      405: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      500: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  coverage_summary_portfolio_summary_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioSummaryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioCoverageSummary"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      404: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      405: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      500: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  summary_overview_portfolio_overview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioSummaryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioOverview"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      404: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      405: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      500: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  stream_qa_answer_qa_stream_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QaRequest"];
      };
    };
    responses: {
      /** @description Server-Sent Events: meta → delta* → (end | error) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream":
            | components["schemas"]["QaMetaEvent"]
            | components["schemas"]["QaDeltaEvent"]
            | components["schemas"]["QaEndEvent"]
            | components["schemas"]["QaErrorEvent"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      404: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      405: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      429: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      500: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Coverly API error */
      404: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      405: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      500: {
        headers: {
          /** @description Server-generated identifier for safe error correlation. */
          "X-Request-ID"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
}
