/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/policies/parse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Parse Policy */
    post: operations["parse_policy_policies_parse_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Portfolio Session */
    post: operations["create_portfolio_session_portfolio_sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/sessions/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh Portfolio Session */
    post: operations["refresh_portfolio_session_portfolio_sessions_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/sessions/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Delete Portfolio Session */
    post: operations["delete_portfolio_session_portfolio_sessions_delete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Coverage Summary */
    post: operations["coverage_summary_portfolio_summary_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/qa/stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ask Portfolio Question Stream
     * @description Stream the answer as Server-Sent Events: progress* → meta → delta* → end.
     */
    post: operations["ask_portfolio_question_stream_qa_stream_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActualLossCoverageItem */
    ActualLossCoverageItem: {
      /** Policy Id */
      policy_id: string | null;
      /** Insurer */
      insurer: string | null;
      /** Product Name */
      product_name: string | null;
      /** Coverage Name */
      coverage_name: string;
      /** Normalized Name */
      normalized_name: string;
      /**
       * Coverage Domain
       * @enum {string}
       */
      coverage_domain:
        | "medical_expense"
        | "travel_medical_expense"
        | "legal_cost"
        | "property_damage"
        | "liability"
        | "auto"
        | "other";
      /** Is Medical Indemnity */
      is_medical_indemnity: boolean;
      /** Is Damage Policy */
      is_damage_policy: boolean;
      /** Duplicate Across Contracts */
      duplicate_across_contracts: boolean;
      /**
       * Original Amount
       * @default
       */
      original_amount: string;
      /**
       * Major Category
       * @default 기타
       */
      major_category: string;
    };
    /** ApiErrorDetail */
    ApiErrorDetail: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /** Request Id */
      request_id: string;
    };
    /** ApiErrorResponse */
    ApiErrorResponse: {
      error: components["schemas"]["ApiErrorDetail"];
    };
    /** Body_parse_policy_policies_parse_post */
    Body_parse_policy_policies_parse_post: {
      /** File */
      file: string;
      /** Password */
      password?: string | null;
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
    };
    /** ClaimChannelBlock */
    ClaimChannelBlock: {
      /** Insurers */
      insurers?: components["schemas"]["ClaimChannelInsurer"][];
      medical_indemnity?:
        components["schemas"]["ClaimChannelMedicalIndemnity"] | null;
    };
    /** ClaimChannelInsurer */
    ClaimChannelInsurer: {
      /** Name */
      name: string;
      /** Customer Center */
      customer_center?: string | null;
      /** Note */
      note?: string | null;
      /** Links */
      links?: components["schemas"]["ClaimChannelLink"][];
    };
    /** ClaimChannelLink */
    ClaimChannelLink: {
      /** Label */
      label: string;
      /** Url */
      url: string;
    };
    /** ClaimChannelMedicalIndemnity */
    ClaimChannelMedicalIndemnity: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Call Center */
      call_center?: string | null;
      /** Links */
      links?: components["schemas"]["ClaimChannelLink"][];
    };
    /** ConversationMessage */
    ConversationMessage: {
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant";
      /** Content */
      content: string;
    };
    /**
     * Coverage
     * @description One coverage (담보) row for the /policies/parse response.
     *
     *     보장내용 is the policy's own wording (authoritative); 해설 is a generated
     *     general explanation, filled only when 보장내용 is absent.
     */
    Coverage: {
      /** 담보명 */
      "\uB2F4\uBCF4\uBA85": string;
      /** 가입금액 */
      "\uAC00\uC785\uAE08\uC561": string;
      /** 보장내용 */
      "\uBCF4\uC7A5\uB0B4\uC6A9": string | null;
      /** 해설 */
      "\uD574\uC124": string | null;
      /**
       * 유형
       * @enum {string}
       */
      "\uC720\uD615"?: "담보" | "부가";
    };
    /** CoverageGroup */
    CoverageGroup: {
      /** Label */
      label: string;
      /**
       * Tone
       * @enum {string}
       */
      tone: "confirmed" | "review" | "limited";
      /** Detail */
      detail: string;
      /** Coverage Names */
      coverage_names?: string[];
      /** Total Amount */
      total_amount?: number | null;
    };
    /** CoveragePeriod */
    CoveragePeriod: {
      /** 시작일 */
      "\uC2DC\uC791\uC77C"?: string;
      /** 종료일 */
      "\uC885\uB8CC\uC77C"?: string;
    };
    /** CoverageSourceItem */
    CoverageSourceItem: {
      /** Policy Id */
      policy_id: string | null;
      /** Insurer */
      insurer: string | null;
      /** Product Name */
      product_name: string | null;
      /** Coverage Name */
      coverage_name: string;
      /** Amount */
      amount: number;
      /** Original Amount */
      original_amount: string;
    };
    /** CoverageTotalItem */
    CoverageTotalItem: {
      /** Normalizedname */
      normalizedName: string;
      /** Category */
      category: string;
      /** Majorcategory */
      majorCategory: string;
      /** Totalamount */
      totalAmount: number;
      /** Coveragecount */
      coverageCount: number;
      /** Composition */
      composition: components["schemas"]["CoverageSourceItem"][];
    };
    /** DamageCoverageGroup */
    DamageCoverageGroup: {
      /** Insurance Type */
      insurance_type: string;
      /** Policies */
      policies: components["schemas"]["DamagePolicyCoverageGroup"][];
    };
    /** DamageCoverageItem */
    DamageCoverageItem: {
      /** Coverage Name */
      coverage_name: string;
      /** Original Amount */
      original_amount: string;
      /**
       * Major Category
       * @default 기타
       */
      major_category: string;
    };
    /** DamagePolicyCoverageGroup */
    DamagePolicyCoverageGroup: {
      /** Policy Id */
      policy_id: string | null;
      /** Insurer */
      insurer?: string | null;
      /** Product Name */
      product_name?: string | null;
      /** Coverages */
      coverages: components["schemas"]["DamageCoverageItem"][];
    };
    /** DeathBenefitGuideInput */
    DeathBenefitGuideInput: {
      /**
       * Has Dependent Family
       * @default false
       */
      has_dependent_family: boolean;
      /**
       * Has Minor Children
       * @default false
       */
      has_minor_children: boolean;
      /**
       * Has Major Debt
       * @default false
       */
      has_major_debt: boolean;
    };
    /** EssentialCoverageCheck */
    EssentialCoverageCheck: {
      /** Items */
      items: components["schemas"]["EssentialCoverageItem"][];
    };
    /** EssentialCoverageItem */
    EssentialCoverageItem: {
      /**
       * Kind
       * @enum {string}
       */
      kind:
        | "death"
        | "cancer"
        | "cerebrovascular"
        | "ischemic_heart"
        | "medical_indemnity";
      /** Label */
      label: string;
      /**
       * Status
       * @enum {string}
       */
      status: "well_prepared" | "needs_review" | "not_found";
      /** Confirmed Amount */
      confirmed_amount?: number | null;
      /** Reference Min Amount */
      reference_min_amount?: number | null;
      /** Reference Max Amount */
      reference_max_amount?: number | null;
      /** Reference Basis */
      reference_basis?: string | null;
      /** Reference Sources */
      reference_sources?: components["schemas"]["ReferenceSource"][];
      /** Reference Amount Label */
      reference_amount_label?: string | null;
      /** Guidance Situation */
      guidance_situation?: string | null;
      /** Guidance Reason */
      guidance_reason?: string | null;
      /** Coverage Count */
      coverage_count: number;
      /** Detail */
      detail: string;
      /** Matched Coverage Names */
      matched_coverage_names?: string[];
      /** Coverage Groups */
      coverage_groups?: components["schemas"]["CoverageGroup"][];
    };
    /** ExcludedCoverageItem */
    ExcludedCoverageItem: {
      /** Policy Id */
      policy_id: string | null;
      /** Coverage Name */
      coverage_name: string;
      /** Original Amount */
      original_amount: string;
      /** Reason */
      reason: string;
      /** Insurer */
      insurer?: string | null;
      /** Product Name */
      product_name?: string | null;
      /**
       * Major Category
       * @default 기타
       */
      major_category: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * InsuredDemographics
     * @description Minimal non-identifying insured context used for personalization.
     */
    "InsuredDemographics-Input": {
      /** Age */
      age?: number | null;
      /**
       * Gender
       * @default 미상
       * @enum {string}
       */
      gender: "남성" | "여성" | "기타" | "미상";
      /**
       * Source
       * @default unknown
       * @enum {string}
       */
      source: "policy" | "user" | "unknown";
      /**
       * Status
       * @default missing
       * @enum {string}
       */
      status:
        | "verified_policy"
        | "user_provided"
        | "conflict_user_override"
        | "conflict"
        | "missing";
    };
    /**
     * InsuredDemographics
     * @description Non-identifying insured attributes derived locally from the policy.
     */
    "InsuredDemographics-Output": {
      /** 나이 */
      "\uB098\uC774": number;
      /**
       * 성별
       * @enum {string}
       */
      "\uC131\uBCC4": "남성" | "여성";
      /**
       * 생애단계
       * @enum {string}
       */
      "\uC0DD\uC560\uB2E8\uACC4": "어린이" | "성인" | "시니어";
    };
    /** PolicyParseResponse */
    PolicyParseResponse: {
      /**
       * Status
       * @constant
       */
      status: "accepted";
      /** Documentid */
      documentId: string;
      /** 문자수 */
      "\uBB38\uC790\uC218": number;
      "\uAE30\uBCF8\uC815\uBCF4": components["schemas"]["PolicySummary"];
      /** 보장목록 */
      "\uBCF4\uC7A5\uBAA9\uB85D": components["schemas"]["Coverage"][];
      /**
       * 분석상태
       * @enum {string}
       */
      "\uBD84\uC11D\uC0C1\uD0DC": "완료" | "부분";
    };
    /** PolicySummary */
    PolicySummary: {
      /** 보험사 */
      "\uBCF4\uD5D8\uC0AC"?: string;
      /** 상품명 */
      "\uC0C1\uD488\uBA85"?: string;
      /** 증권번호 */
      "\uC99D\uAD8C\uBC88\uD638"?: string;
      /** 계약자 */
      "\uACC4\uC57D\uC790"?: string;
      /** 피보험자 */
      "\uD53C\uBCF4\uD5D8\uC790"?: string;
      "\uBCF4\uD5D8\uAE30\uAC04"?: components["schemas"]["CoveragePeriod"];
      /** 만기일 */
      "\uB9CC\uAE30\uC77C"?: string;
      /** 납입기간 */
      "\uB0A9\uC785\uAE30\uAC04"?: string;
      "\uBCF4\uD5D8\uB8CC"?: components["schemas"]["PremiumSummary"];
      "\uD53C\uBCF4\uD5D8\uC790\uC815\uBCF4"?: components["schemas"]["InsuredDemographics-Output"];
      "\uCC28\uB7C9\uC815\uBCF4"?: components["schemas"]["VehicleInfo"];
      /** 보험분류 */
      "\uBCF4\uD5D8\uBD84\uB958"?: string;
      /** 상품태그 */
      "\uC0C1\uD488\uD0DC\uADF8"?: string[];
    };
    /** PortfolioCoverageSummary */
    PortfolioCoverageSummary: {
      /** Totals */
      totals: components["schemas"]["CoverageTotalItem"][];
      /** Actual Loss Coverages */
      actual_loss_coverages: components["schemas"]["ActualLossCoverageItem"][];
      /** Excluded Coverages */
      excluded_coverages: components["schemas"]["ExcludedCoverageItem"][];
      /** Damage Coverages */
      damage_coverages?: components["schemas"]["DamageCoverageGroup"][];
      /** Excluded Auto Policy Count */
      excluded_auto_policy_count: number;
      essential_coverage_check?: components["schemas"]["EssentialCoverageCheck"];
      /** Special Policy Analyses */
      special_policy_analyses?: components["schemas"]["SpecialPolicyAnalysis"][];
      claim_channels?: components["schemas"]["ClaimChannelBlock"] | null;
      premium?: components["schemas"]["PremiumOverview"] | null;
      premium_benchmark?: components["schemas"]["PremiumBenchmark"] | null;
      overview?: components["schemas"]["PortfolioOverview"] | null;
    };
    /** PortfolioOverview */
    PortfolioOverview: {
      /**
       * Generation
       * @constant
       */
      generation: "llm";
      /** Title */
      title: string;
      /** Paragraphs */
      paragraphs?: string[];
      /** Takeaways */
      takeaways?: components["schemas"]["PortfolioOverviewTakeaway"][];
    };
    /** PortfolioOverviewTakeaway */
    PortfolioOverviewTakeaway: {
      /** Label */
      label: string;
      /** Title */
      title: string;
      /** Detail */
      detail: string;
    };
    /** PortfolioQuestionRequest */
    PortfolioQuestionRequest: {
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
      /** Policyids */
      policyIds: string[];
      /** Question */
      question: string;
      demographics?: components["schemas"]["InsuredDemographics-Input"];
      /** History */
      history?: components["schemas"]["ConversationMessage"][];
    };
    /** PortfolioSessionDeleteResponse */
    PortfolioSessionDeleteResponse: {
      /** Status */
      status: string;
    };
    /** PortfolioSessionRequest */
    PortfolioSessionRequest: {
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
    };
    /** PortfolioSessionResponse */
    PortfolioSessionResponse: {
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
      /** Expiresat */
      expiresAt: string;
    };
    /** PortfolioSummaryRequest */
    PortfolioSummaryRequest: {
      /** Portfoliosessiontoken */
      portfolioSessionToken: string;
      /** Policyids */
      policyIds: string[];
      death_benefit_context?: components["schemas"]["DeathBenefitGuideInput"];
    };
    /** PremiumBenchmark */
    PremiumBenchmark: {
      /** Age Band Label */
      age_band_label: string;
      /** Min Age */
      min_age: number;
      /** Max Age */
      max_age: number;
      /** Average Monthly Income */
      average_monthly_income: number;
      /** Suggested Min Ratio */
      suggested_min_ratio: number;
      /** Suggested Max Ratio */
      suggested_max_ratio: number;
      /** Suggested Min Premium */
      suggested_min_premium: number;
      /** Suggested Max Premium */
      suggested_max_premium: number;
      income_source: components["schemas"]["PremiumBenchmarkSource"];
      guide_source: components["schemas"]["PremiumBenchmarkSource"];
    };
    /** PremiumBenchmarkSource */
    PremiumBenchmarkSource: {
      /** Label */
      label: string;
      /** Url */
      url: string;
      /** Published At */
      published_at: string;
      /**
       * Reliability
       * @enum {string}
       */
      reliability:
        | "official"
        | "public_research"
        | "industry"
        | "large_private_analysis"
        | "private_guidance";
      /** Caveat */
      caveat: string;
    };
    /** PremiumOverview */
    PremiumOverview: {
      /** Monthly Total */
      monthly_total: number;
      /** Monthly Policy Count */
      monthly_policy_count: number;
      /** Unconfirmed Policy Count */
      unconfirmed_policy_count: number;
      /** Items */
      items: components["schemas"]["PremiumPolicyItem"][];
    };
    /** PremiumPolicyItem */
    PremiumPolicyItem: {
      /** Policy Id */
      policy_id: string | null;
      /** Insurer */
      insurer: string | null;
      /** Product Name */
      product_name: string | null;
      /** Monthly Amount */
      monthly_amount: number | null;
      /** Cycle */
      cycle: string | null;
    };
    /** PremiumSummary */
    PremiumSummary: {
      /** 금액 */
      "\uAE08\uC561"?: number;
      /** 납입주기 */
      "\uB0A9\uC785\uC8FC\uAE30"?: string;
    };
    /** ReferenceSource */
    ReferenceSource: {
      /** Label */
      label: string;
      /** Url */
      url: string;
      /** Published At */
      published_at: string;
      /**
       * Reliability
       * @enum {string}
       */
      reliability:
        | "official"
        | "public_research"
        | "industry"
        | "large_private_analysis"
        | "private_guidance";
      /** Caveat */
      caveat: string;
    };
    /** RequestValidationErrorDetail */
    RequestValidationErrorDetail: {
      /** Loc */
      loc: (string | number)[];
      /** Msg */
      msg: string;
      /** Type */
      type: string;
    } & {
      [key: string]: unknown;
    };
    /** RequestValidationErrorResponse */
    RequestValidationErrorResponse: {
      /** Detail */
      detail: components["schemas"]["RequestValidationErrorDetail"][];
    };
    /** SpecialCoverageCheck */
    SpecialCoverageCheck: {
      /** Label */
      label: string;
      /**
       * Status
       * @enum {string}
       */
      status: "confirmed" | "not_found";
      /** Detail */
      detail: string;
      /** Matched Coverage Names */
      matched_coverage_names?: string[];
    };
    /** SpecialPolicyAnalysis */
    SpecialPolicyAnalysis: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "auto" | "driver" | "travel" | "fire";
      /** Label */
      label: string;
      /** Policy Count */
      policy_count: number;
      /** Product Names */
      product_names?: string[];
      /** Confirmed Coverage Names */
      confirmed_coverage_names?: string[];
      /** Classification Reasons */
      classification_reasons?: string[];
      /** Overview */
      overview: string;
      /** Coverage Checks */
      coverage_checks?: components["schemas"]["SpecialCoverageCheck"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * VehicleInfo
     * @description Vehicle details extracted from policy summary.
     */
    VehicleInfo: {
      /** 차량명 */
      "\uCC28\uB7C9\uBA85"?: string;
      /** 차량번호 */
      "\uCC28\uB7C9\uBC88\uD638"?: string;
      /** 연식 */
      "\uC5F0\uC2DD"?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  parse_policy_policies_parse_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_parse_policy_policies_parse_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PolicyParseResponse"];
        };
      };
      /** @description Coverly API error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Coverly API error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["ApiErrorResponse"]
            | components["schemas"]["RequestValidationErrorResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  create_portfolio_session_portfolio_sessions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioSessionResponse"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  refresh_portfolio_session_portfolio_sessions_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioSessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioSessionResponse"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  delete_portfolio_session_portfolio_sessions_delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioSessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioSessionDeleteResponse"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  coverage_summary_portfolio_summary_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioSummaryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioCoverageSummary"];
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  ask_portfolio_question_stream_qa_stream_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioQuestionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Coverly API error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description Coverly API error */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorResponse"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
