/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import type { components } from "./generated";

type ApiErrorCode = components["schemas"]["ApiErrorCode"];
type PolicyClassification = components["schemas"]["PolicySummary"]["보험분류"];

export const API_ERROR_CODES = [
  "PDF_TOO_LARGE",
  "PDF_PAGE_LIMIT_EXCEEDED",
  "PDF_COMPLEXITY_LIMIT_EXCEEDED",
  "PDF_PARSING_BUSY",
  "INVALID_PDF",
  "PDF_PASSWORD_REQUIRED",
  "PDF_PASSWORD_INCORRECT",
  "PDF_TEXT_EXTRACTION_FAILED",
  "reference_data_unavailable",
  "portfolio_overview_unavailable",
  "INVALID_PORTFOLIO_SESSION",
  "PORTFOLIO_DOCUMENT_LIMIT_EXCEEDED",
  "COUNSEL_TURN_LIMIT_REACHED",
  "POLICY_UPLOAD_IN_PROGRESS",
  "POLICY_UPLOAD_ALREADY_COMPLETED",
  "POLICY_UPLOAD_CANCELLED",
  "portfolio_session_unavailable",
  "INVALID_POLICY_SELECTION",
  "REQUEST_VALIDATION_ERROR",
  "INVALID_MULTIPART_REQUEST",
  "HTTP_ERROR",
  "INTERNAL_SERVER_ERROR",
] as const satisfies readonly ApiErrorCode[];
export const POLICY_CLASSIFICATIONS = [
  "생명보험",
  "제3보험",
  "손해보험",
  "미분류",
] as const satisfies readonly PolicyClassification[];
export const PORTFOLIO_MAX_DOCUMENTS = 5 as const;
export const PDF_MAX_BYTES = 10485760 as const;

export const QA_STREAM_JSON_SCHEMA = {
  schema: {
    oneOf: [
      { $ref: "#/components/schemas/QaMetaEvent" },
      { $ref: "#/components/schemas/QaDeltaEvent" },
      { $ref: "#/components/schemas/QaEndEvent" },
      { $ref: "#/components/schemas/QaErrorEvent" },
    ],
    title: "Response 200 Stream Qa Answer Qa Stream Post",
    discriminator: {
      propertyName: "type",
      mapping: {
        meta: "#/components/schemas/QaMetaEvent",
        delta: "#/components/schemas/QaDeltaEvent",
        end: "#/components/schemas/QaEndEvent",
        error: "#/components/schemas/QaErrorEvent",
      },
    },
  },
  components: {
    schemas: {
      QaDeltaEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["delta"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
          text: { type: "string", title: "Text" },
        },
        type: "object",
        required: ["text", "type"],
        title: "QaDeltaEvent",
      },
      QaEndEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["end"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
        },
        type: "object",
        title: "QaEndEvent",
        required: ["type"],
      },
      QaErrorEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["error"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
          code: { type: "string", const: "QA_STREAM_FAILED", title: "Code" },
          message: { type: "string", title: "Message" },
          request_id: { type: "string", title: "Request Id" },
          retryable: { type: "boolean", title: "Retryable" },
        },
        type: "object",
        required: ["code", "message", "request_id", "retryable", "type"],
        title: "QaErrorEvent",
      },
      QaMetaEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["meta"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
          in_scope: { type: "boolean", title: "In Scope" },
          answered_question: { type: "string", title: "Answered Question" },
          excluded_note: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Excluded Note",
          },
          turns_remaining: { type: "integer", title: "Turns Remaining" },
        },
        type: "object",
        required: [
          "in_scope",
          "answered_question",
          "excluded_note",
          "turns_remaining",
          "type",
        ],
        title: "QaMetaEvent",
      },
    },
  },
} as const;

const apiErrorCodeSet: ReadonlySet<string> = new Set(API_ERROR_CODES);

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === "string" && apiErrorCodeSet.has(value);
}
