/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import type { components } from "./generated";

type ApiErrorCode = components["schemas"]["ApiErrorCode"];
type QaAnswerStatus = components["schemas"]["QaAnswerStatus"];
type QaGenerationMode = components["schemas"]["QaMetaEvent"]["generation"];
type PolicyClassification = components["schemas"]["PolicySummary"]["보험분류"];

export const API_ERROR_CODES = [
  "PDF_TOO_LARGE",
  "INVALID_PDF",
  "PDF_PASSWORD_REQUIRED",
  "PDF_PASSWORD_INCORRECT",
  "PDF_TEXT_EXTRACTION_FAILED",
  "reference_data_unavailable",
  "INVALID_PORTFOLIO_SESSION",
  "PORTFOLIO_DOCUMENT_LIMIT_EXCEEDED",
  "POLICY_UPLOAD_CANCELLED",
  "portfolio_session_unavailable",
  "INVALID_POLICY_SELECTION",
  "REQUEST_VALIDATION_ERROR",
  "INVALID_MULTIPART_REQUEST",
] as const satisfies readonly ApiErrorCode[];
export const QA_ANSWER_STATUSES = [
  "answered",
  "refused",
  "no_data",
  "clarify",
] as const satisfies readonly QaAnswerStatus[];
export const QA_GENERATION_MODES = [
  "llm",
  "fallback",
] as const satisfies readonly QaGenerationMode[];
export const POLICY_CLASSIFICATIONS = [
  "생명보험",
  "제3보험",
  "손해보험",
  "미분류",
] as const satisfies readonly PolicyClassification[];

export const QA_STREAM_JSON_SCHEMA = {
  schema: {
    oneOf: [
      { $ref: "#/components/schemas/QaProgressEvent" },
      { $ref: "#/components/schemas/QaMetaEvent" },
      { $ref: "#/components/schemas/QaDeltaEvent" },
      { $ref: "#/components/schemas/QaEndEvent" },
    ],
    title: "Response 200 Ask Portfolio Question Stream Qa Stream Post",
    discriminator: {
      propertyName: "type",
      mapping: {
        progress: "#/components/schemas/QaProgressEvent",
        meta: "#/components/schemas/QaMetaEvent",
        delta: "#/components/schemas/QaDeltaEvent",
        end: "#/components/schemas/QaEndEvent",
      },
    },
  },
  components: {
    schemas: {
      AnswerCitation: {
        properties: {
          evidence_id: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Evidence Id",
          },
          policy_id: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Policy Id",
          },
          insurer: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Insurer",
          },
          product_name: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Product Name",
          },
          coverage_name: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Coverage Name",
          },
          source_id: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Source Id",
          },
          source_title: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Source Title",
          },
          source_category: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Source Category",
          },
          source_url: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Source Url",
          },
          source_page: {
            anyOf: [{ type: "integer", minimum: 1 }, { type: "null" }],
            title: "Source Page",
          },
          source_version: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Source Version",
          },
        },
        type: "object",
        required: ["policy_id", "insurer", "product_name"],
        title: "AnswerCitation",
      },
      ClaimChannelBlock: {
        properties: {
          insurers: {
            items: { $ref: "#/components/schemas/ClaimChannelInsurer" },
            type: "array",
            title: "Insurers",
          },
          medical_indemnity: {
            anyOf: [
              { $ref: "#/components/schemas/ClaimChannelMedicalIndemnity" },
              { type: "null" },
            ],
          },
        },
        type: "object",
        title: "ClaimChannelBlock",
      },
      ClaimChannelInsurer: {
        properties: {
          name: { type: "string", title: "Name" },
          customer_center: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Customer Center",
          },
          note: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Note",
          },
          links: {
            items: { $ref: "#/components/schemas/ClaimChannelLink" },
            type: "array",
            title: "Links",
          },
        },
        type: "object",
        required: ["name"],
        title: "ClaimChannelInsurer",
      },
      ClaimChannelLink: {
        properties: {
          label: { type: "string", title: "Label" },
          url: { type: "string", title: "Url" },
        },
        type: "object",
        required: ["label", "url"],
        title: "ClaimChannelLink",
      },
      ClaimChannelMedicalIndemnity: {
        properties: {
          name: { type: "string", title: "Name" },
          description: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Description",
          },
          call_center: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Call Center",
          },
          links: {
            items: { $ref: "#/components/schemas/ClaimChannelLink" },
            type: "array",
            title: "Links",
          },
        },
        type: "object",
        required: ["name"],
        title: "ClaimChannelMedicalIndemnity",
      },
      QaAnswerStatus: {
        type: "string",
        enum: ["answered", "refused", "no_data", "clarify"],
      },
      QaDeltaEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["delta"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
          text: { type: "string", title: "Text" },
        },
        type: "object",
        required: ["type", "text"],
        title: "QaDeltaEvent",
      },
      QaEndEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["end"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
          status: { $ref: "#/components/schemas/QaAnswerStatus" },
          generation: {
            type: "string",
            enum: ["llm", "fallback"],
            title: "Generation",
          },
          citations: {
            items: { $ref: "#/components/schemas/AnswerCitation" },
            type: "array",
            title: "Citations",
          },
          limitations: {
            items: { type: "string" },
            type: "array",
            title: "Limitations",
          },
          suggestions: {
            items: { type: "string" },
            type: "array",
            title: "Suggestions",
          },
          claim_channels: {
            anyOf: [
              { $ref: "#/components/schemas/ClaimChannelBlock" },
              { type: "null" },
            ],
          },
        },
        type: "object",
        required: [
          "type",
          "status",
          "generation",
          "citations",
          "limitations",
          "suggestions",
          "claim_channels",
        ],
        title: "QaEndEvent",
      },
      QaMetaEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["meta"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
          status: { $ref: "#/components/schemas/QaAnswerStatus" },
          generation: {
            type: "string",
            enum: ["llm", "fallback"],
            title: "Generation",
          },
        },
        type: "object",
        required: ["type", "status", "generation"],
        title: "QaMetaEvent",
      },
      QaProgressEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["progress"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
          stage: { type: "string", title: "Stage" },
          text: { type: "string", title: "Text" },
        },
        type: "object",
        required: ["type", "stage", "text"],
        title: "QaProgressEvent",
      },
    },
  },
} as const;

const apiErrorCodeSet: ReadonlySet<string> = new Set(API_ERROR_CODES);
const qaAnswerStatusSet: ReadonlySet<string> = new Set(QA_ANSWER_STATUSES);
const qaGenerationModeSet: ReadonlySet<string> = new Set(QA_GENERATION_MODES);

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === "string" && apiErrorCodeSet.has(value);
}

export function isQaAnswerStatus(value: unknown): value is QaAnswerStatus {
  return typeof value === "string" && qaAnswerStatusSet.has(value);
}

export function isQaGenerationMode(value: unknown): value is QaGenerationMode {
  return typeof value === "string" && qaGenerationModeSet.has(value);
}
