/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import type { components } from "./generated";

type ApiErrorCode = components["schemas"]["ApiErrorCode"];
type PolicyClassification = components["schemas"]["PolicySummary"]["보험분류"];

export const API_ERROR_CODES = [
  "PDF_TOO_LARGE",
  "INVALID_PDF",
  "PDF_PASSWORD_REQUIRED",
  "PDF_PASSWORD_INCORRECT",
  "PDF_TEXT_EXTRACTION_FAILED",
  "reference_data_unavailable",
  "INVALID_PORTFOLIO_SESSION",
  "PORTFOLIO_DOCUMENT_LIMIT_EXCEEDED",
  "COUNSEL_TURN_LIMIT_REACHED",
  "POLICY_UPLOAD_CANCELLED",
  "portfolio_session_unavailable",
  "INVALID_POLICY_SELECTION",
  "REQUEST_VALIDATION_ERROR",
  "INVALID_MULTIPART_REQUEST",
] as const satisfies readonly ApiErrorCode[];
export const POLICY_CLASSIFICATIONS = [
  "생명보험",
  "제3보험",
  "손해보험",
  "미분류",
] as const satisfies readonly PolicyClassification[];

export const COUNSEL_STREAM_JSON_SCHEMA = {
  schema: {
    oneOf: [
      { $ref: "#/components/schemas/CounselMetaEvent" },
      { $ref: "#/components/schemas/CounselDeltaEvent" },
      { $ref: "#/components/schemas/CounselEndEvent" },
    ],
    title: "Response 200 Stream Counsel Answer Counsel Stream Post",
    discriminator: {
      propertyName: "type",
      mapping: {
        meta: "#/components/schemas/CounselMetaEvent",
        delta: "#/components/schemas/CounselDeltaEvent",
        end: "#/components/schemas/CounselEndEvent",
      },
    },
  },
  components: {
    schemas: {
      CounselDeltaEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["delta"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
          text: { type: "string", title: "Text" },
        },
        type: "object",
        required: ["text", "type"],
        title: "CounselDeltaEvent",
      },
      CounselEndEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["end"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
        },
        type: "object",
        title: "CounselEndEvent",
        required: ["type"],
      },
      CounselMetaEvent: {
        properties: {
          type: {
            type: "string",
            enum: ["meta"],
            description:
              "discriminator enum property added by openapi-typescript",
          },
          in_scope: { type: "boolean", title: "In Scope" },
          rewritten_question: { type: "string", title: "Rewritten Question" },
          excluded_note: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Excluded Note",
          },
          turns_remaining: { type: "integer", title: "Turns Remaining" },
        },
        type: "object",
        required: [
          "in_scope",
          "rewritten_question",
          "excluded_note",
          "turns_remaining",
          "type",
        ],
        title: "CounselMetaEvent",
      },
    },
  },
} as const;

const apiErrorCodeSet: ReadonlySet<string> = new Set(API_ERROR_CODES);

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === "string" && apiErrorCodeSet.has(value);
}
